[platformio]
default_envs = esp32

[env:esp32]
platform = espressif32
board = lolin32
framework = arduino
extra_scripts = merge_firmware.py

monitor_speed = 115200
upload_speed = 921600

build_flags =
  -std=gnu++17
  -Wall

build_unflags =
  -std=gnu++11
  -ggdb

lib_deps =
  knolleary/PubSubClient @ ^2.8
  electroniccats/MPU6050 @ ^0.6.0
